/**
 * ============================================
 * GuardianSync v2.0 - Student Model
 * ============================================
 * 
 * CRUCIAL DESIGN DECISION:
 * This schema stores face_encoding (128-float array) and photo_url,
 * NOT raw Base64 image data. This prevents database bloat and
 * enables efficient face comparison.
 * 
 * The face encoding is generated by the Python AI service
 * and stored here for quick retrieval during face scans.
 */

import mongoose from 'mongoose';

// ============================================
// Schema Definition
// ============================================

const studentSchema = new mongoose.Schema({
  // Basic Information
  name: {
    type: String,
    required: [true, 'Student name is required'],
    trim: true,
    maxlength: [100, 'Name cannot exceed 100 characters'],
    index: 'text', // Enable text search
  },
  
  // Student identifier (school-specific)
  studentId: {
    type: String,
    required: [true, 'Student ID is required'],
    unique: true,
    trim: true,
    uppercase: true,
    index: true,
  },
  
  grade: {
    type: String,
    required: [true, 'Grade is required'],
    trim: true,
  },
  
  section: {
    type: String,
    trim: true,
  },
  
  // Direct parent info (for simple admin form)
  parentName: {
    type: String,
    trim: true,
    maxlength: [100, 'Parent name cannot exceed 100 characters'],
  },
  
  parentPhone: {
    type: String,
    trim: true,
  },
  
  parentEmail: {
    type: String,
    trim: true,
    lowercase: true,
  },
  
  dateOfBirth: {
    type: Date,
  },
  
  // ============================================
  // FACE RECOGNITION DATA
  // ============================================
  // IMPORTANT: We store the encoding, NOT the raw image
  
  /**
   * Face encoding - 128-dimensional vector from face_recognition library.
   * This is the ONLY biometric data stored in the database.
   * Generated by the Python AI service.
   */
  faceEncoding: {
    type: [Number],
    validate: {
      validator: function(arr) {
        // Face encoding must be exactly 128 floats (or empty if not set)
        return arr.length === 0 || arr.length === 128;
      },
      message: 'Face encoding must be exactly 128 dimensions'
    },
    default: [],
    select: false, // Don't return by default for privacy
  },
  
  /**
   * URL to the student's photo stored in cloud storage (S3/Cloudinary).
   * The actual image is NEVER stored in the database.
   */
  photoUrl: {
    type: String,
    default: null,
  },
  
  /**
   * Timestamp when face encoding was last updated.
   * Useful for tracking when biometric data needs refresh.
   */
  faceEncodingUpdatedAt: {
    type: Date,
    default: null,
  },
  
  /**
   * Flag indicating if face encoding is available and valid.
   */
  hasFaceEncoding: {
    type: Boolean,
    default: false,
    index: true,
  },
  
  // ============================================
  // RELATIONSHIPS
  // ============================================
  
  // Parent/Guardian references
  parents: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }],
  
  // Primary guardian for notifications
  primaryGuardian: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  
  // Assigned bus route
  assignedBus: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Bus',
    index: true,
  },
  
  // ============================================
  // TRACKING STATUS
  // ============================================
  
  /**
   * Current boarding status.
   * Updated when face is scanned during pickup/dropoff.
   */
  boardingStatus: {
    type: String,
    enum: ['not_boarded', 'morning_picked_up', 'at_school', 'evening_picked_up', 'dropped_home', 'absent'],
    default: 'not_boarded',
    index: true,
  },
  
  /**
   * Timestamp of last boarding event.
   */
  lastBoardingEvent: {
    timestamp: Date,
    scanType: {
      type: String,
      enum: ['morning_pickup', 'morning_dropoff', 'evening_pickup', 'evening_dropoff'],
    },
    location: {
      type: {
        type: String,
        enum: ['Point'],
      },
      coordinates: [Number], // [longitude, latitude]
    },
    busId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bus',
    },
    verifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  },
  
  // ============================================
  // ATTENDANCE HISTORY (Four-Step Commute Tracking)
  // ============================================
  
  /**
   * Daily attendance records.
   * Tracks the four-step commute: Morning Pickup → School Dropoff → Evening Pickup → Home Dropoff
   */
  attendanceHistory: [{
    date: {
      type: Date,
      required: true,
      index: true,
    },
    // Morning cycle: Home → School
    morningPickup: {
      scanned: { type: Boolean, default: false },
      timestamp: Date,
      location: {
        type: { type: String, enum: ['Point'] },
        coordinates: [Number],
      },
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      busId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus' },
    },
    morningDropoff: {
      scanned: { type: Boolean, default: false },
      timestamp: Date,
      location: {
        type: { type: String, enum: ['Point'] },
        coordinates: [Number],
      },
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      busId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus' },
    },
    // Evening cycle: School → Home
    eveningPickup: {
      scanned: { type: Boolean, default: false },
      timestamp: Date,
      location: {
        type: { type: String, enum: ['Point'] },
        coordinates: [Number],
      },
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      busId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus' },
    },
    eveningDropoff: {
      scanned: { type: Boolean, default: false },
      timestamp: Date,
      location: {
        type: { type: String, enum: ['Point'] },
        coordinates: [Number],
      },
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      busId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bus' },
    },
    // Flags
    markedAbsent: { type: Boolean, default: false },
    absentReason: String,
    anomalies: [{
      type: { type: String },
      message: String,
      timestamp: Date,
    }],
  }],
  
  // ============================================
  // PICKUP/DROPOFF LOCATIONS
  // ============================================
  
  pickupLocation: {
    address: String,
    coordinates: {
      type: {
        type: String,
        enum: ['Point'],
      },
      coordinates: [Number], // [longitude, latitude]
    },
    notes: String,
  },
  
  dropoffLocation: {
    address: String,
    coordinates: {
      type: {
        type: String,
        enum: ['Point'],
      },
      coordinates: [Number],
    },
    notes: String,
  },
  
  // ============================================
  // ADMINISTRATIVE
  // ============================================
  
  isActive: {
    type: Boolean,
    default: true,
    index: true,
  },
  
  notes: {
    type: String,
    maxlength: [500, 'Notes cannot exceed 500 characters'],
  },
  
  // Medical/special needs (for driver awareness)
  specialNeeds: {
    hasSpecialNeeds: { type: Boolean, default: false },
    details: String,
  },

}, {
  timestamps: true,
  toJSON: {
    virtuals: true,
    transform: function(doc, ret) {
      // Never expose face encoding in JSON by default
      delete ret.faceEncoding;
      delete ret.__v;
      return ret;
    }
  }
});

// ============================================
// Indexes for Performance
// ============================================

// Compound index for common queries
studentSchema.index({ assignedBus: 1, isActive: 1, boardingStatus: 1 });
studentSchema.index({ 'parents': 1 });

// Geospatial indexes for location queries
studentSchema.index({ 'pickupLocation.coordinates': '2dsphere' });
studentSchema.index({ 'dropoffLocation.coordinates': '2dsphere' });

// ============================================
// Virtual Properties
// ============================================

/**
 * Get display name with grade.
 */
studentSchema.virtual('displayName').get(function() {
  return `${this.name} (Grade ${this.grade})`;
});

// ============================================
// Instance Methods
// ============================================

/**
 * Update face encoding data.
 * Called after successful face registration.
 * 
 * @param {number[]} encoding - 128-dimensional face encoding
 * @param {string} photoUrl - URL to stored photo
 */
studentSchema.methods.updateFaceEncoding = async function(encoding, photoUrl) {
  this.faceEncoding = encoding;
  this.photoUrl = photoUrl;
  this.hasFaceEncoding = true;
  this.faceEncodingUpdatedAt = new Date();
  await this.save();
};

/**
 * Update boarding status with Four-Step Commute tracking.
 * Creates event record in attendance history and triggers notifications.
 * 
 * @param {string} scanType - One of: morning_pickup, morning_dropoff, evening_pickup, evening_dropoff
 * @param {Object} eventData - Event details { location, busId, verifiedBy }
 * @returns {Object} - { success, message, attendanceRecord }
 */
studentSchema.methods.updateBoardingStatus = async function(scanType, eventData = {}) {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  
  // Find or create today's attendance record
  let todayRecord = this.attendanceHistory.find(
    record => record.date.getTime() === today.getTime()
  );
  
  if (!todayRecord) {
    todayRecord = {
      date: today,
      morningPickup: { scanned: false },
      morningDropoff: { scanned: false },
      eveningPickup: { scanned: false },
      eveningDropoff: { scanned: false },
      markedAbsent: false,
      anomalies: [],
    };
    this.attendanceHistory.push(todayRecord);
    todayRecord = this.attendanceHistory[this.attendanceHistory.length - 1];
  }
  
  // Map scan type to status and field
  const scanMapping = {
    morning_pickup: { status: 'morning_picked_up', field: 'morningPickup' },
    morning_dropoff: { status: 'at_school', field: 'morningDropoff' },
    evening_pickup: { status: 'evening_picked_up', field: 'eveningPickup' },
    evening_dropoff: { status: 'dropped_home', field: 'eveningDropoff' },
  };
  
  const mapping = scanMapping[scanType];
  if (!mapping) {
    throw new Error(`Invalid scan type: ${scanType}`);
  }
  
  // Update the specific scan field
  todayRecord[mapping.field] = {
    scanned: true,
    timestamp: now,
    location: eventData.location,
    verifiedBy: eventData.verifiedBy,
    busId: eventData.busId,
  };
  
  // Update current status
  this.boardingStatus = mapping.status;
  this.lastBoardingEvent = {
    timestamp: now,
    scanType: scanType,
    ...eventData,
  };
  
  await this.save();
  
  return {
    success: true,
    scanType,
    status: mapping.status,
    attendanceRecord: todayRecord,
  };
};

/**
 * Validate if a scan type is allowed based on the Four-Step Commute logic.
 * 
 * Rules:
 * - morning_pickup: Always allowed (starts the day)
 * - morning_dropoff: Requires morning_pickup first
 * - evening_pickup: Requires morning_dropoff first (student must be at school)
 * - evening_dropoff: Requires evening_pickup first
 * 
 * @param {string} scanType - The scan type to validate
 * @returns {Object} - { valid, message, requiredPrevious }
 */
studentSchema.methods.validateScanSequence = function(scanType) {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  
  // Find today's attendance record
  const todayRecord = this.attendanceHistory.find(
    record => record.date && record.date.getTime() === today.getTime()
  );
  
  // Define the validation rules
  const validationRules = {
    morning_pickup: {
      requiredPrevious: null,
      check: () => true,
      message: 'Morning pickup can always be recorded',
    },
    morning_dropoff: {
      requiredPrevious: 'morning_pickup',
      check: () => todayRecord?.morningPickup?.scanned === true,
      message: 'Cannot record morning dropoff without morning pickup. Student was not picked up this morning.',
    },
    evening_pickup: {
      requiredPrevious: 'morning_dropoff',
      check: () => todayRecord?.morningDropoff?.scanned === true,
      message: 'Cannot record evening pickup. Student was not dropped off at school this morning.',
    },
    evening_dropoff: {
      requiredPrevious: 'evening_pickup',
      check: () => todayRecord?.eveningPickup?.scanned === true,
      message: 'Cannot record evening dropoff without evening pickup. Student was not picked up from school.',
    },
  };
  
  const rule = validationRules[scanType];
  if (!rule) {
    return { valid: false, message: `Invalid scan type: ${scanType}` };
  }
  
  // Check if already scanned
  const fieldMapping = {
    morning_pickup: 'morningPickup',
    morning_dropoff: 'morningDropoff',
    evening_pickup: 'eveningPickup',
    evening_dropoff: 'eveningDropoff',
  };
  
  if (todayRecord?.[fieldMapping[scanType]]?.scanned) {
    return {
      valid: false,
      message: `${scanType.replace('_', ' ')} already recorded for today`,
      alreadyScanned: true,
    };
  }
  
  const isValid = rule.check();
  return {
    valid: isValid,
    message: isValid ? 'Scan allowed' : rule.message,
    requiredPrevious: rule.requiredPrevious,
  };
};

/**
 * Get today's attendance record.
 * 
 * @returns {Object|null} - Today's attendance record or null
 */
studentSchema.methods.getTodayAttendance = function() {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  
  return this.attendanceHistory.find(
    record => record.date && record.date.getTime() === today.getTime()
  ) || null;
};

/**
 * Clear face encoding (for GDPR compliance or re-registration).
 */
studentSchema.methods.clearFaceEncoding = async function() {
  this.faceEncoding = [];
  this.hasFaceEncoding = false;
  this.faceEncodingUpdatedAt = null;
  // Note: photoUrl is kept for reference, but can be deleted from storage
  await this.save();
};

// ============================================
// Static Methods
// ============================================

/**
 * Find all students with face encodings for comparison.
 * Used during face scan to get comparison candidates.
 * 
 * @param {ObjectId} busId - Optional: filter by bus
 * @returns {Promise<Array>} Students with id and encoding
 */
studentSchema.statics.getEncodingsForComparison = async function(busId = null) {
  const query = {
    hasFaceEncoding: true,
    isActive: true,
  };
  
  if (busId) {
    query.assignedBus = busId;
  }
  
  const students = await this.find(query)
    .select('_id name studentId faceEncoding assignedBus')
    .lean();
  
  return students.map(s => ({
    id: s._id.toString(),
    name: s.name,
    studentId: s.studentId,
    encoding: s.faceEncoding,
    busId: s.assignedBus?.toString(),
  }));
};

/**
 * Find students by assigned bus.
 * 
 * @param {ObjectId} busId - Bus ID
 * @returns {Promise<Student[]>}
 */
studentSchema.statics.findByBus = function(busId) {
  return this.find({ assignedBus: busId, isActive: true })
    .populate('primaryGuardian', 'name phone email');
};

/**
 * Find students by parent.
 * 
 * @param {ObjectId} parentId - Parent user ID
 * @returns {Promise<Student[]>}
 */
studentSchema.statics.findByParent = function(parentId) {
  return this.find({ parents: parentId, isActive: true })
    .populate('assignedBus', 'busNumber routeName');
};

// ============================================
// Export Model
// ============================================

const Student = mongoose.model('Student', studentSchema);

export default Student;
